---
# tasks file for vpc_flow_logs
- set_fact: env_var="{{ lookup('env','WORKSPACE') }}"

- name: launch vpc_flow_log cft template
  cloudformation:
    stack_name: "ansible-vpcflowlog1"
    state: "present"
    region: "{{region}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    disable_rollback: true
    template: "{{ env_var }}/roles/vpc_flow_logs/files/VPCFlowLog.template.json"
    template_parameters:
      VPCId: "{{ VPCId }}"
    tags:
      Stack: "ansible-cloudformation1"