---
# vars file for ec2

aws_access_key:
aws_secret_key:
aws_resource_tags: {
 'Name': 'ansible-test',
 'Backup': 'Yes',
 'CC_Code': '12345',
 'Project_Name': '',
 'Sub_Process': '',
 'Server_Owner': '',
 'Owner_Supervisor': '',
 'Stack': '',
 'Stop': '',
 'Alert_Notification': '',
 'Hardened': 'True' }
region: ap-south-1
state: present
username: ubuntu
ec2_sg_id: ['sg-6f9dea07']
ec2_vpc_subnet_id: subnet-7c2b4d31
ec2_vpc_id: vpc-1566777c
ec2_key_name: minjar-test
ec2_assign_public_ip: yes
ec2_find_ami_name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-2017*"
ec2_instance_type: t2.micro
#ec2_instance_profile_name: aws-elasticbeanstalk-ec2-role
ec2_base_image: ami-336b4456
#ansible_server_ip: 
#ec2_user_data: |
#   docker run nginx
project_name: my-ami
build_version: 1
project_build: "{{ project_name }}-{{ build_version}}"
ec2_volumes:
  - device_name: /dev/sda1
    volume_type: gp2
    volume_size: 8
    delete_on_termination: true
  - device_name: /dev/sdb
    volume_type: gp2
    volume_size: 4
    delete_on_termination: true