---

- name: Get nat gateways with specific filter
  ec2_vpc_nat_gateway_facts:
    region: "{{ delete_vpc_region }}"
    filters:
      vpc-id: "{{ delete_vpc_id }}"
  register: gateways_to_remove

- name: Delete nat gateway using discovered nat gateways from facts module.
  ec2_vpc_nat_gateway:
    state: absent
    region: "{{ vpc_region }}"
    wait: yes
    nat_gateway_id: "{{ item.nat_gateway_id }}"
    release_eip: yes
  register: delete_nat_gateway_result
  with_items: "{{ gateways_to_remove.result }}"

- name: Delete VPC
  ec2_vpc:
    state: "{{ delete_vpc_state }}"
    vpc_id: "{{ delete_vpc_id }}"   
    resource_tags: "{{ vpc_resource_tags }}"
    region: "{{ delete_vpc_region }}"    
  # with_items:
  #   - "{{ delete_vpc }}"
