---

- name: Empty old file
  file:
    path: /tmp/list.csv
    state: absent

- set_fact:
    region: "{{ regions | difference(skip_region) }}"

- name: Create list of default vpc's with region
  shell: AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{aws_secret_key}}" aws ec2 describe-vpcs --region {{ item }} --filters Name=isDefault,Values=true --query 'Vpcs[0].VpcId' --output text | awk '{print $1":{{ item }}"}' >> /tmp/list.csv && sed -i '/None/d' /tmp/list.csv
  with_items:
    - "{{ region }}"
  register: vpc_list

- name: Remove default VPC
  ec2_vpc:
    state: "{{ delete_default_vpc_state }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    vpc_id: "{{ item.split(':')[0] }}"
    region: "{{ item.split(':')[1] }}"
    resource_tags: { "Name":"" }  
  with_lines:
    - 'cat /tmp/list.csv'
  when: item.split(':')[0] != 'None'
  ignore_errors: yes
  
- name: Delete vpc list
  file:
    path: /tmp/list.csv
    state: absent